<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'rapture\\form\\render' => '/../src/Render.php',
                'rapture\\helper\\arrays' => '/../src/Arrays.php',
                'rapture\\helper\\country' => '/../src/Country.php',
                'rapture\\helper\\definition\\rabbitcommandtrait' => '/../src/Definition/RabbitCommandTrait.php',
                'rapture\\helper\\html' => '/../src/Html.php',
                'rapture\\helper\\locale' => '/../src/Locale.php',
                'rapture\\helper\\strings' => '/../src/Strings.php',
                'rapture\\helper\\time' => '/../src/Time.php',
                'rapture\\template\\assets' => '/../src/Assets.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
